// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NaderProductsApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210233205_AddReturnTotalToCashierInvoices")]
    partial class AddReturnTotalToCashierInvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashierInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("text")
                        .HasColumnName("customername");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text")
                        .HasColumnName("customerphone");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("discounttotal");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("grandtotal");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoicedate");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("issuspended");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymentmethod");

                    b.Property<decimal>("ReturnTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("VatTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("vattotal");

                    b.HasKey("Id");

                    b.ToTable("cashierinvoices", (string)null);
                });

            modelBuilder.Entity("CashierInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<bool>("HasOffer")
                        .HasColumnType("boolean")
                        .HasColumnName("hasoffer");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("invoiceid");

                    b.Property<string>("OfferName")
                        .HasColumnType("text")
                        .HasColumnName("offername");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasColumnName("productname");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<bool>("TaxIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("taxincluded");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("cashierinvoiceitems", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("Barcode");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("Category");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpiryDate");

                    b.Property<bool>("IsVatIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("IsVatIncluded");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("MinQuantity");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<bool>("OfferEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("OfferEnabled");

                    b.Property<DateTime?>("OfferEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OfferEnd");

                    b.Property<string>("OfferName")
                        .HasColumnType("text")
                        .HasColumnName("OfferName");

                    b.Property<decimal?>("OfferPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("OfferPrice");

                    b.Property<DateTime?>("OfferStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OfferStart");

                    b.Property<bool>("OfferVatIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("OfferVatIncluded");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("PurchasePrice");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("SalePrice");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("SoldQuantity");

                    b.Property<string>("SupplierName")
                        .HasColumnType("text")
                        .HasColumnName("SupplierName");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("CashierInvoiceItem", b =>
                {
                    b.HasOne("CashierInvoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
