--
-- PostgreSQL database dump
--

\restrict FdE7HZLs9Ba5dYqRQqUKkfBoHgsjwxjsVfyHofBBjncJD1bgyVDpoS5iGgxoAxS

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: CashierInvoiceItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CashierInvoiceItems" (
    "Id" integer NOT NULL,
    "CashierInvoiceId" integer NOT NULL,
    "ProductId" integer,
    "Barcode" text,
    "ProductName" text NOT NULL,
    "Quantity" double precision NOT NULL,
    "UnitPrice" double precision NOT NULL,
    "Discount" double precision NOT NULL,
    "TaxIncluded" boolean NOT NULL,
    "HasOffer" boolean NOT NULL,
    "OfferName" text
);


ALTER TABLE public."CashierInvoiceItems" OWNER TO postgres;

--
-- Name: CashierInvoiceItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CashierInvoiceItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CashierInvoiceItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CashierInvoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CashierInvoices" (
    "Id" integer NOT NULL,
    "InvoiceDate" timestamp with time zone NOT NULL,
    "PaymentMethod" text NOT NULL,
    "CustomerId" integer,
    "CustomerName" text,
    "CustomerPhone" text,
    "IsSuspended" boolean NOT NULL,
    "Notes" text,
    "SubTotal" double precision NOT NULL,
    "VatTotal" double precision NOT NULL,
    "DiscountTotal" double precision NOT NULL,
    "GrandTotal" double precision NOT NULL,
    "ReturnAmount" double precision NOT NULL
);


ALTER TABLE public."CashierInvoices" OWNER TO postgres;

--
-- Name: CashierInvoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CashierInvoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CashierInvoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CustomerInvoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CustomerInvoices" (
    "Id" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "Amount" double precision NOT NULL,
    "Description" text NOT NULL,
    "Date" text NOT NULL
);


ALTER TABLE public."CustomerInvoices" OWNER TO postgres;

--
-- Name: CustomerInvoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CustomerInvoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CustomerInvoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CustomerPayments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CustomerPayments" (
    "Id" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "Amount" double precision NOT NULL,
    "Method" text NOT NULL,
    "Note" text,
    "Date" text NOT NULL
);


ALTER TABLE public."CustomerPayments" OWNER TO postgres;

--
-- Name: CustomerPayments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CustomerPayments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CustomerPayments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Customers" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Phone" text,
    "Address" text,
    "Notes" text,
    "Status" text NOT NULL
);


ALTER TABLE public."Customers" OWNER TO postgres;

--
-- Name: Customers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Customers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Customers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Expenses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Expenses" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Statement" text NOT NULL,
    "Amount" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Expenses" OWNER TO postgres;

--
-- Name: Expenses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Expenses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Expenses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Barcode" text NOT NULL,
    "Name" text NOT NULL,
    "SupplierName" text,
    "Category" text,
    "Quantity" integer NOT NULL,
    "MinQuantity" integer NOT NULL,
    "SoldQuantity" integer NOT NULL,
    "PurchasePrice" double precision NOT NULL,
    "SalePrice" double precision NOT NULL,
    "IsVatIncluded" boolean NOT NULL,
    "ExpiryDate" text,
    "OfferEnabled" boolean NOT NULL,
    "OfferName" text,
    "OfferPrice" double precision,
    "OfferVatIncluded" boolean NOT NULL,
    "OfferStart" text,
    "OfferEnd" text
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: CashierInvoiceItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CashierInvoiceItems" ("Id", "CashierInvoiceId", "ProductId", "Barcode", "ProductName", "Quantity", "UnitPrice", "Discount", "TaxIncluded", "HasOffer", "OfferName") FROM stdin;
2	2	1	6652184268421	بيبسي	0	12	0	t	t	اليوم الوطني
3	3	1	6652184268421	بيبسي	0	12	0	t	t	اليوم الوطني
4	4	1	6652184268421	بيبسي	0	12	0	t	t	اليوم الوطني
5	5	1	6652184268421	بيبسي	1	12	0	t	t	اليوم الوطني
6	6	2	101708	كوكا كولا	1	2	0	t	t	اليوم الوطني
\.


--
-- Data for Name: CashierInvoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CashierInvoices" ("Id", "InvoiceDate", "PaymentMethod", "CustomerId", "CustomerName", "CustomerPhone", "IsSuspended", "Notes", "SubTotal", "VatTotal", "DiscountTotal", "GrandTotal", "ReturnAmount") FROM stdin;
2	2025-12-22 11:01:02.225565+00	deferred	1	\N	\N	f	\N	10.43	1.57	0	12	12
3	2025-12-22 18:40:43.243902+00	card	\N	\N	\N	f	\N	10.43	1.57	0	12	12
4	2025-12-22 18:43:32.041119+00	deferred	2	\N	\N	f	\N	10.43	1.57	0	12	12
5	2025-12-22 20:59:51.878936+00	deferred	2	\N	\N	f	\N	10.43	1.57	0	12	0
6	2025-12-22 21:09:12.739755+00	deferred	2	\N	\N	f	\N	1.74	0.26	0	2	0
\.


--
-- Data for Name: CustomerInvoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CustomerInvoices" ("Id", "CustomerId", "Amount", "Description", "Date") FROM stdin;
3	2	12	فاتورة كاشير رقم 4	2025-12-22T21:43:32
4	2	-12	مرتجع فاتورة كاشير رقم 4	2025-12-22T21:44:00
5	2	12	فاتورة كاشير رقم 5	2025-12-22T23:59:52
6	2	2	فاتورة كاشير رقم 6	2025-12-23T00:09:13
\.


--
-- Data for Name: CustomerPayments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CustomerPayments" ("Id", "CustomerId", "Amount", "Method", "Note", "Date") FROM stdin;
\.


--
-- Data for Name: Customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Customers" ("Id", "Name", "Phone", "Address", "Notes", "Status") FROM stdin;
2	خالد	0500000000	طريف		active
\.


--
-- Data for Name: Expenses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Expenses" ("Id", "Date", "Statement", "Amount", "CreatedAt", "UpdatedAt") FROM stdin;
2	2025-12-23 00:00:00+00	ايجار محل	2000	2025-12-22 22:41:48.957047+00	2025-12-23 09:01:51.360735+00
\.


--
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Products" ("Id", "Barcode", "Name", "SupplierName", "Category", "Quantity", "MinQuantity", "SoldQuantity", "PurchasePrice", "SalePrice", "IsVatIncluded", "ExpiryDate", "OfferEnabled", "OfferName", "OfferPrice", "OfferVatIncluded", "OfferStart", "OfferEnd") FROM stdin;
1	6652184268421	بيبسي	طالب	مشروبات	99	10	1	10	20	t	2026-01-28	t	اليوم الوطني	12	t	2025-11-30	2025-12-28
2	101708	كوكا كولا	خالد	مشروبات	49	10	1	1.5	2.5	t	2026-01-20	t	اليوم الوطني	2	t	2025-11-30	2025-12-28
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251222104043_FixCashierInvoiceRelation	9.0.0
\.


--
-- Name: CashierInvoiceItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CashierInvoiceItems_Id_seq"', 6, true);


--
-- Name: CashierInvoices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CashierInvoices_Id_seq"', 6, true);


--
-- Name: CustomerInvoices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CustomerInvoices_Id_seq"', 6, true);


--
-- Name: CustomerPayments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CustomerPayments_Id_seq"', 1, true);


--
-- Name: Customers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Customers_Id_seq"', 2, true);


--
-- Name: Expenses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Expenses_Id_seq"', 2, true);


--
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 2, true);


--
-- Name: CashierInvoiceItems PK_CashierInvoiceItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CashierInvoiceItems"
    ADD CONSTRAINT "PK_CashierInvoiceItems" PRIMARY KEY ("Id");


--
-- Name: CashierInvoices PK_CashierInvoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CashierInvoices"
    ADD CONSTRAINT "PK_CashierInvoices" PRIMARY KEY ("Id");


--
-- Name: CustomerInvoices PK_CustomerInvoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CustomerInvoices"
    ADD CONSTRAINT "PK_CustomerInvoices" PRIMARY KEY ("Id");


--
-- Name: CustomerPayments PK_CustomerPayments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CustomerPayments"
    ADD CONSTRAINT "PK_CustomerPayments" PRIMARY KEY ("Id");


--
-- Name: Customers PK_Customers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");


--
-- Name: Expenses PK_Expenses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Expenses"
    ADD CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id");


--
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_CashierInvoiceItems_CashierInvoiceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CashierInvoiceItems_CashierInvoiceId" ON public."CashierInvoiceItems" USING btree ("CashierInvoiceId");


--
-- Name: IX_CustomerInvoices_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CustomerInvoices_CustomerId" ON public."CustomerInvoices" USING btree ("CustomerId");


--
-- Name: IX_CustomerPayments_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CustomerPayments_CustomerId" ON public."CustomerPayments" USING btree ("CustomerId");


--
-- Name: CashierInvoiceItems FK_CashierInvoiceItems_CashierInvoices_CashierInvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CashierInvoiceItems"
    ADD CONSTRAINT "FK_CashierInvoiceItems_CashierInvoices_CashierInvoiceId" FOREIGN KEY ("CashierInvoiceId") REFERENCES public."CashierInvoices"("Id") ON DELETE CASCADE;


--
-- Name: CustomerInvoices FK_CustomerInvoices_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CustomerInvoices"
    ADD CONSTRAINT "FK_CustomerInvoices_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: CustomerPayments FK_CustomerPayments_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CustomerPayments"
    ADD CONSTRAINT "FK_CustomerPayments_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict FdE7HZLs9Ba5dYqRQqUKkfBoHgsjwxjsVfyHofBBjncJD1bgyVDpoS5iGgxoAxS

